### ISSUE TITLE
Error: ** (UndefinedFunctionError) function :libsecp256k1.ecdsa_sign_compact/4 is undefined (module :libsecp256k1 is not available)

### ISSUE THREAD

**Issue by masonforest** [exthereum/ex_devp2p#8]
I get an error when running `mix test`:

** (UndefinedFunctionError) function :libsecp256k1.ecdsa_recover_compact/4 is undefined (module :libsecp256k1 is not available)

Full test log [here](https://gist.github.com/masonforest/642599d920153f958b8a407758108f40).

**Comment by masonforest** [comment]
from gitter: you need to manually compile `libsecp256k1` to fix this:

    cd deps/libsecp256k1 && rebar compile

We should either fix in `libsecp256k1` or add that step to the installation docs

**Comment by hayesgm** [comment]
yeah, this is pretty consistent. I strongly suggest we just re-write `ecdsa_recover` in raw Elixir and drop this library entirely. The math isn't hard in and of itself.
